site_name: Статический сайт на MkDocs
site_description: Учебный проект по созданию и развертыванию статических сайтов с кастомной темой
site_author: Anastasiia
site_url: https://adzhevelik.github.io/PyWeb/

theme:
  name: null
  custom_dir: custom_theme
  
nav:
  - Главная: index.md
  - О проекте: about.md
  - Отчет 2.1: report.md
  - Отчет 2.2: report2.md

markdown_extensions:
  - admonition
  - codehilite:
      linenums: false
  - toc:
      permalink: false
  - tables
  - fenced_code
